#Parameters to be defined by the user
#Custom VPC, Subnets and security groups determined by the user.
Parameters: 
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VpcId of your current Virtual Private Cloud that you wish to use" 
    Default: Select A VPC
    
  PublicSubnet:
    Description: "Which public subnet would you like to use? "
    Type: AWS::EC2::Subnet::Id
    Default: Select a Public Subnet
    
  PrivateSubnet: 
    Description: "Which private subnet would you like to use?"
    Type: AWS::EC2::Subnet::Id
    Default: Select a Private Subnet
   
  BastionHostSG:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security Group to apply to your bastion host" 
    Default: Select a Public Security Group
    
  AppServerSG:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security group for app server in private subnet"
    Default: Select a Private Security Group

#Mapping used for the AMI depending on the region
Mappings:
  Region2AMI:
    us-east-1:
      alinuxhvm: ami-026b57f3c383c2eec
    eu-east-1:
      alinuxhvm: ami-026b57f3c383c2eec

#Resources launched in this template, public bastion host instance and a private EC2 App server.  
Resources: 
 NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
        KeyName: MyKeyPair

 EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
        InstanceType: t2.micro
        KeyName: !Ref NewKeyPair
        SubnetId: !Ref PublicSubnet
        ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', alinuxhvm]
        SecurityGroupIds: 
            - Ref: BastionHostSG
        Tags:
            - Key: "Name"
              Value: "EC2 Bastion Host"
        
 EC2InstancePrivate:
    Type: AWS::EC2::Instance
    Properties:
        InstanceType: t2.micro
        SubnetId: !Ref PrivateSubnet
        ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', alinuxhvm]
        SecurityGroupIds: 
            - Ref: AppServerSG
        Tags:
            - Key: "Name"
              Value: "EC2 App Server"
              
#Attaching an ElasticIP for the public instance.               
 ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc
        InstanceId: !Ref EC2Instance