Parameters:
    VpcId:
        Type: AWS::EC2::VPC::Id
        Description: "VpcId of your current Virtual Private Cloud that you wish to use" 
        Default: vpc-0442d7f979fcd6a41
    
    PublicSubnet:
        Description: "Which public subnet would you like to use? "
        Type: AWS::EC2::Subnet::Id
        Default: subnet-0b167c837f132d877

Resources:
  SecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
        VpcId: !Ref VpcId
        GroupDescription: Security Group for the Bastion Host
        GroupName: "Bastion Host Security Group"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 1.1.1.1/32